import React from 'react';
import '../styles/AIAnalysisInsights.css';

interface AIAnalysisInsightsProps {
  analysis?: {
    metaTrends: string[];
    keyInsights: string[];
    confidence: number;
    dataQuality: string;
  };
}

export const AIAnalysisInsights: React.FC<AIAnalysisInsightsProps> = ({ analysis }) => {
  if (!analysis) {
    return null;
  }

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 80) return '#10b981'; // Green
    if (confidence >= 60) return '#f59e0b'; // Yellow
    return '#ef4444'; // Red
  };

  const getDataQualityColor = (quality: string) => {
    switch (quality.toLowerCase()) {
      case 'high':
        return '#10b981';
      case 'good':
        return '#3b82f6';
      case 'medium':
        return '#f59e0b';
      case 'low':
        return '#ef4444';
      default:
        return '#6b7280';
    }
  };

  return (
    <div className="ai-analysis-insights">
      <div className="insights-header">
        <h3>🤖 AI Analysis Overview</h3>
        <div className="insights-metrics">
          <div className="metric">
            <span className="metric-label">Confidence:</span>
            <span 
              className="metric-value confidence"
              style={{ color: getConfidenceColor(analysis.confidence) }}
            >
              {analysis.confidence}%
            </span>
          </div>
          <div className="metric">
            <span className="metric-label">Data Quality:</span>
            <span 
              className="metric-value quality"
              style={{ color: getDataQualityColor(analysis.dataQuality) }}
            >
              {analysis.dataQuality}
            </span>
          </div>
        </div>
      </div>

      {analysis.metaTrends && analysis.metaTrends.length > 0 && (
        <div className="insights-section">
          <h4>📈 Meta Trends</h4>
          <div className="trends-list">
            {analysis.metaTrends.map((trend, index) => (
              <div key={index} className="trend-item">
                <span className="trend-icon">→</span>
                <span className="trend-text">{trend}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {analysis.keyInsights && analysis.keyInsights.length > 0 && (
        <div className="insights-section">
          <h4>💡 Key Insights</h4>
          <div className="insights-list">
            {analysis.keyInsights.map((insight, index) => (
              <div key={index} className="insight-item">
                <span className="insight-icon">💎</span>
                <span className="insight-text">{insight}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="insights-footer">
        <p className="ai-disclaimer">
          💡 These insights are generated by AI analysis of the current meta data. 
          Use them alongside your own research for the best results.
        </p>
      </div>
    </div>
  );
}; 